name: Continuous Integration

on:
  push:
    branches: [ main, dev, 'features/*' ]
  pull_request:
    branches: [ main, dev ]

env:
  DOTNET_VERSION: '9.0.x'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore spec-driven-vibe-coding-challenge-orchestrator-code.sln
      
    - name: Build solution
      run: dotnet build spec-driven-vibe-coding-challenge-orchestrator-code.sln --configuration Release --no-restore
      
    - name: Run unit tests
      run: |
        echo "Running unit tests (fast feedback)..."
        dotnet test tests/mcp-server-kb-content-fetcher.unit-tests/mcp-server-kb-content-fetcher.unit-tests.csproj \
          --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
        dotnet test tests/orchestrator-agent.unit-tests/orchestrator-agent.unit-tests.csproj \
          --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
          
    - name: Run integration tests
      run: |
        echo "Running integration tests (slower, external interactions / protocol)..."
        dotnet test tests/mcp-server-kb-content-fetcher.integration-tests/mcp-server-kb-content-fetcher.integration-tests.csproj \
          --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
        dotnet test tests/orchestrator-agent.integration-tests/orchestrator-agent.integration-tests.csproj \
          --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
          
    - name: Run smoke tests
      run: |
        echo "Running smoke tests..."
        dotnet test tests/orchestrator-agent.smoke-tests/orchestrator-agent.smoke-tests.csproj \
          --configuration Release --no-build --verbosity normal --logger trx --results-directory TestResults
          
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: .NET Test Results
        path: TestResults/*.trx
        reporter: dotnet-trx
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: TestResults/
        retention-days: 7

  code-quality:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Restore dependencies
      run: dotnet restore spec-driven-vibe-coding-challenge-orchestrator-code.sln
      
    - name: Check formatting
      run: dotnet format spec-driven-vibe-coding-challenge-orchestrator-code.sln --verify-no-changes --verbosity diagnostic
      
    - name: Security scan (if NuGet packages have vulnerabilities)
      run: dotnet list package --vulnerable --include-transitive 2>&1 | tee vulnerable-packages.log
      continue-on-error: true
      
    - name: Upload security scan results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-scan
        path: vulnerable-packages.log
        retention-days: 7